/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Panel.java to edit this template
 */
package restopetalosdesol.Vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Panel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import restopetalosdesol.Vistas.Comida2;

/**
 *
 * @author RODRI
 */
public class CartaComida extends java.awt.Panel {

    /**
     * Creates new form CartaComida
     */
    public CartaComida() {
        initComponents();
        this.setSize(820, 370);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono = new ImageIcon(getClass().getResource("/restopetalosdesol/Recursos/pizza.jpg/"));
        Image imagen = icono.getImage();
        contenedor = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            } };
            jButton2 = new javax.swing.JButton();

            setBackground(new java.awt.Color(255, 255, 255));
            setPreferredSize(new java.awt.Dimension(820, 370));
            addComponentListener(new java.awt.event.ComponentAdapter() {
                public void componentMoved(java.awt.event.ComponentEvent evt) {
                    formComponentMoved(evt);
                }
            });
            setLayout(new java.awt.CardLayout());

            jButton2.setText("Next >");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
            contenedor.setLayout(contenedorLayout);
            contenedorLayout.setHorizontalGroup(
                contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                    .addContainerGap(684, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addGap(31, 31, 31))
            );
            contenedorLayout.setVerticalGroup(
                contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(jButton2)
                    .addContainerGap(150, Short.MAX_VALUE))
            );

            add(contenedor, "card2");
        }// </editor-fold>//GEN-END:initComponents

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentMoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Comida2 o=new Comida2();
        o.setSize(820, 360);
        o.setLocation(0, 0);
        contenedor.removeAll();
        contenedor.add(o, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
